name: "Security Tests"

on:
  pull_request:
    branches:
      - '**'

permissions:
  checks: write
  contents: read
  id-token: write

env:
  HUSKY: 0
  BRIGHT_HOSTNAME: development.playground.brightsec.com
  BRIGHT_PROJECT_ID: 7AJ1f4Ricmd2MWrrzdoh57
  BRIGHT_TARGET_URL: http://127.0.0.1:3000

jobs:
  security-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Disable prepare script (husky)
        run: npm pkg delete scripts.prepare

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Install SecTester dependencies
        run: npm i --save-dev @sectester/core @sectester/repeater @sectester/scan @sectester/runner

      - name: Start application
        run: docker compose --file=compose.local.yml up -d

      - name: Wait for application to be ready
        run: |
          until nc -zv 127.0.0.1 3000; do
            echo "Waiting for application to be ready..."
            sleep 5
          done

      - name: Configure Bright credentials
        uses: ./.github/workflows/composite/configure-bright-credentials
        with:
          BRIGHT_HOSTNAME: ${{ env.BRIGHT_HOSTNAME }}
          BRIGHT_PROJECT_ID: ${{ env.BRIGHT_PROJECT_ID }}
          BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}

      - name: Run security tests
        env:
          BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node --experimental-transform-types --experimental-strip-types --experimental-detect-module \
          --disable-warning=MODULE_TYPELESS_PACKAGE_JSON --disable-warning=ExperimentalWarning \
          --test-force-exit --test .brightsec/tests/*.test.ts --test-concurrency=4
